### ISSUE TITLE
Training Logs

### ISSUE THREAD

**Issue by innat** [wangermeng2021/SnapMix-tensorflow2#2]
Can you share the training logs and activated visual maps while doing `SmapMix`? Are you able to reproduce the official results? I think, using `SmapMix` with a custom data generator probably can slow down the training time. 

---

FYI, There is another interesting augmentation - [here](https://stackoverflow.com/questions/65181294/how-to-create-class-label-for-mosaic-augmentation-in-image-classification); in case you're interested.

**Comment by wangermeng2021** [comment]
Sorry for late replay, because of time pressure ,I only test it  on car dataset, yes, I can reproduce  the official results.
You are right, SnapMix  slow down the training time, because it take two forward pass, first forward pass is for training ,the second  forward pass is for creating class activation map.
Thank you for your feedback, I will check it ,and add it to project if i have time.
